# Yarn configuration file
# See https://yarnpkg.com/configuration/yarnrc

# Note: nodeOptions is not supported in Yarn 4
# Use NODE_OPTIONS environment variable or specify in package.json scripts if needed

# Enable zero-installs (optional)
# enableGlobalCache: false

# Package resolution settings
# compressionLevel: mixed

nodeLinker: node-modules
