name: Lint and Typecheck

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  setup:
    uses: ./.github/workflows/setup-node-yarn.yml

  lint_and_typecheck:
    name: Lint and Typecheck
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run lint and typecheck
        run: yarn lint

      - name: Run tests
        run: yarn test
